### ISSUE TITLE
ArgumentException: the same key already added.

### ISSUE THREAD

**Issue by ntfrigo** [perrich/Hangfire.MemoryStorage#33]
Hi i get the following error when using the MemoryStorage:

> [ArgumentException: the same key already added.]
>    System.ThrowHelper.ThrowArgumentException(ExceptionResource resource) +60
>    System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add) +5619817
>    System.Linq.Enumerable.ToDictionary(IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer) +302
>    Hangfire.MemoryStorage.MemoryStorageMonitoringApi.GetTimelineStats(List`1 dates, Func`2 formatorAction) +556
>    Hangfire.MemoryStorage.MemoryStorageMonitoringApi.GetHourlyTimelineStats(String type) +229
>    Hangfire.Dashboard.Pages.HomePage.Execute() +368
>    Hangfire.Dashboard.RazorPage.TransformText(String body) +31
>    Hangfire.Dashboard.RazorPageDispatcher.Dispatch(DashboardContext context) +89
>    Hangfire.Dashboard.<>c__DisplayClass1_1.<UseHangfireDashboard>b__1(IDictionary`2 env) +618
>    Microsoft.Owin.Mapping.<Invoke>d__0.MoveNext() +486
>    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() +32
>    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +62
>    Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.<RunApp>d__5.MoveNext() +197
>    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() +32
>    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +62
>    Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.<DoFinalWork>d__2.MoveNext() +184
>    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() +32
>    Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.StageAsyncResult.End(IAsyncResult ar) +118
>    System.Web.AsyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +510
>    System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step) +220
>    System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +134

What could be causing this issue?

**Comment by perrich** [comment]
Without any information, your question cannot be answered. I think it's related to your data.

Can your reproduce it?
- if no, issue cannot be fixed with only the stack trace
- if yes, how (code, data, ...)?

**Comment by ascendedguard** [comment]
Incase it helps, we're getting the same issue lately. In our case, Hangfire had been running for a few hour processing jobs with a max parallel count of 8. Eventually, the jobs stop processing, and trying to access the Hangfire dashboard provides a 500 error with the following error in the logs:

```
2021-04-12 19:13:34.8786|INFO|106|RequestLoggingMiddleware|HTTP GET /hangfire responded 200 in 1.0666 ms, User: (null)||https://localhost/api/hangfire||
2021-04-12 19:13:34.8786|ERROR|106|IISHttpServer|Connection ID "17077649792894510912", Request ID "80002741-0001-ed00-b63f-84710c7967bb": An unhandled exception was thrown by the application.|System.ArgumentException: An item with the same key has already been added. Key: stats:failed:2021-04-12-18
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at Hangfire.MemoryStorage.MemoryStorageMonitoringApi.GetTimelineStats(List`1 dates, Func`2 formatorAction)
   at Hangfire.MemoryStorage.MemoryStorageMonitoringApi.GetHourlyTimelineStats(String type)
   at Hangfire.MemoryStorage.MemoryStorageMonitoringApi.HourlyFailedJobs()
   at Hangfire.Dashboard.Pages.HomePage.Execute()
   at Hangfire.Dashboard.RazorPage.TransformText(String body)
   at Hangfire.Dashboard.RazorPage.ToString()
   at Hangfire.Dashboard.RazorPageDispatcher.Dispatch(DashboardContext context)
   at Hangfire.Dashboard.AspNetCoreDashboardMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at [REDACTED].RequestLoggingMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.UsePathBaseMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContextOfT`1.ProcessRequestAsync()|https://localhost/api/hangfire||
```

**Comment by mtsmith** [comment]
I get the same error often in development where we use in-memory hangfire. In production we're using SQL server and don't see this.

```
An unhandled exception occurred while processing the request.
ArgumentException: An item with the same key has already been added. Key: stats:succeeded:2023-06-25-16
System.Collections.Generic.Dictionary<TKey, TValue>.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
```

```
System.ArgumentException: An item with the same key has already been added. Key: stats:succeeded:2023-06-25-16
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at Hangfire.MemoryStorage.MemoryStorageMonitoringApi.GetTimelineStats(List`1 dates, Func`2 formatorAction)
   at Hangfire.MemoryStorage.MemoryStorageMonitoringApi.GetHourlyTimelineStats(String type)
   at Hangfire.Dashboard.Pages.HomePage.Execute()
   at Hangfire.Dashboard.RazorPage.TransformText(String body)
   at Hangfire.Dashboard.RazorPageDispatcher.Dispatch(DashboardContext context)
   at Hangfire.Dashboard.AspNetCoreDashboardMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.InvokeCore(HttpContext context, PathString matchedPath, PathString remainingPath)
   at Serilog.AspNetCore.RequestLoggingMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

**Comment by perrich** [comment]
Thank you. 

Maybe it's an issue in CountersAggregator.
I'll try to understand the issue.

**Comment by perrich** [comment]
As I thought, it's really a concurrent access issue in CountersAggregator. It will produce two AggregatedCounterDto instead of one.
So, to fix it :
- we can remove the concurrent access (harder)
- we can sum the counter in Hangfire.MemoryStorage.MemoryStorageMonitoringApi.GetTimelineStats() before convert the result to a dictionnary

**Comment by perrich** [comment]
It should be fixed :
https://github.com/perrich/Hangfire.MemoryStorage/commit/f2d6d4888a04cbd6b3195e7469d78142256cc52f

**Comment by emreerkmen** [comment]
Hello, 
I tested a couple of hours and I did not encounter any problem so on. It seems fixed. Thank you.
